import ArgumentParser
import PasswordGenerators

extension Genpass {
    struct Passphrase: ParsableCommand {
        static var configuration = CommandConfiguration(
            abstract: "Generate a passphrase from a set of words."
        )
        
        @OptionGroup
        var commonOptions: CommonOptions
        
        @OptionGroup
        var securityLevelOptions: SecurityLevelOptions
        
        mutating func run() {
            let passwordGenerator = PassphraseGenerator(words: .wordList)
            print(passwords: (0..<commonOptions.count).map { _ in
                passwordGenerator.generatePassword(
                    atSecurityLevel: securityLevelOptions.securityLevel
                )
            }, terminator: commonOptions.terminator)
        }
    }
}

private extension Set<String> {
    static let wordList: Self = [
        "abandon", "ability", "able", "about", "above", "absent", "absorb", "abstract", "absurd",
        "access", "accident", "account", "accuse", "achieve", "acid", "acoustic", "acquire",
        "act", "action", "actor", "actress", "actual", "adapt", "add", "addict", "address",
        "admit", "adult", "advance", "advice", "aerobic", "affair", "afford", "afraid", "again",
        "agent", "agree", "ahead", "aim", "air", "airport", "aisle", "alarm", "album", "alcohol",
        "alien", "all", "alley", "allow", "almost", "alone", "alpha", "already", "also", "alter",
        "amateur", "amazing", "among", "amount", "amused", "analyst", "anchor", "ancient",
        "angle", "angry", "animal", "ankle", "announce", "annual", "another", "answer", "antenna",
        "anxiety", "any", "apart", "apology", "appear", "apple", "approve", "april", "arch",
        "area", "arena", "argue", "arm", "armed", "armor", "army", "around", "arrange", "arrest",
        "arrow", "art", "artefact", "artist", "artwork", "ask", "aspect", "assault", "asset",
        "assume", "asthma", "athlete", "atom", "attack", "attend", "attitude", "attract",
        "audit", "august", "aunt", "author", "auto", "autumn", "average", "avocado", "avoid",
        "aware", "away", "awesome", "awful", "awkward", "axis", "baby", "bachelor", "bacon",
        "bag", "balance", "balcony", "ball", "bamboo", "banana", "banner", "bar", "barely",
        "barrel", "base", "basic", "basket", "battle", "beach", "bean", "beauty", "because",
        "beef", "before", "begin", "behave", "behind", "believe", "below", "belt", "bench",
        "best", "betray", "better", "between", "beyond", "bicycle", "bid", "bike", "bind",
        "bird", "birth", "bitter", "black", "blade", "blame", "blanket", "blast", "bleak",
        "blind", "blood", "blossom", "blouse", "blue", "blur", "blush", "board", "boat", "body",
        "bomb", "bone", "bonus", "book", "boost", "border", "boring", "borrow", "boss", "bottom",
        "box", "boy", "bracket", "brain", "brand", "brass", "brave", "bread", "breeze", "brick",
        "brief", "bright", "bring", "brisk", "broccoli", "broken", "bronze", "broom", "brother",
        "brush", "bubble", "buddy", "budget", "buffalo", "build", "bulb", "bulk", "bullet",
        "bunker", "burden", "burger", "burst", "bus", "business", "busy", "butter", "buyer",
        "cabbage", "cabin", "cable", "cactus", "cage", "cake", "call", "calm", "camera", "camp",
        "canal", "cancel", "candy", "cannon", "canoe", "canvas", "canyon", "capable", "capital",
        "car", "carbon", "card", "cargo", "carpet", "carry", "cart", "case", "cash", "casino",
        "casual", "cat", "catalog", "catch", "category", "cattle", "caught", "cause", "caution",
        "ceiling", "celery", "cement", "census", "century", "cereal", "certain", "chair", "chalk",
        "change", "chaos", "chapter", "charge", "chase", "chat", "cheap", "check", "cheese",
        "cherry", "chest", "chicken", "chief", "child", "chimney", "choice", "choose", "chronic",
        "chunk", "churn", "cigar", "cinnamon", "circle", "citizen", "city", "civil", "claim",
        "clarify", "claw", "clay", "clean", "clerk", "clever", "click", "client", "cliff",
        "clinic", "clip", "clock", "clog", "close", "cloth", "cloud", "clown", "club", "clump",
        "clutch", "coach", "coast", "coconut", "code", "coffee", "coil", "coin", "collect",
        "column", "combine", "come", "comfort", "comic", "common", "company", "concert",
        "confirm", "congress", "connect", "consider", "control", "convince", "cook", "cool",
        "copy", "coral", "core", "corn", "correct", "cost", "cotton", "couch", "country",
        "course", "cousin", "cover", "coyote", "crack", "cradle", "craft", "cram", "crane",
        "crater", "crawl", "crazy", "cream", "credit", "creek", "crew", "cricket", "crime",
        "critic", "crop", "cross", "crouch", "crowd", "crucial", "cruel", "cruise", "crumble",
        "crush", "cry", "crystal", "cube", "culture", "cup", "cupboard", "curious", "current",
        "curve", "cushion", "custom", "cute", "cycle", "dad", "damage", "damp", "dance", "danger",
        "dash", "daughter", "dawn", "day", "deal", "debate", "debris", "decade", "december",
        "decline", "decorate", "decrease", "deer", "defense", "define", "defy", "degree", "delay",
        "demand", "demise", "denial", "dentist", "deny", "depart", "depend", "deposit", "depth",
        "derive", "describe", "desert", "design", "desk", "despair", "destroy", "detail",
        "develop", "device", "devote", "diagram", "dial", "diamond", "diary", "dice", "diesel",
        "differ", "digital", "dignity", "dilemma", "dinner", "dinosaur", "direct", "dirt",
        "discover", "disease", "dish", "dismiss", "disorder", "display", "distance", "divert",
        "divorce", "dizzy", "doctor", "document", "dog", "doll", "dolphin", "domain", "donate",
        "donor", "door", "dose", "double", "dove", "draft", "dragon", "drama", "drastic", "draw",
        "dress", "drift", "drill", "drink", "drip", "drive", "drop", "drum", "dry", "duck",
        "dune", "during", "dust", "dutch", "duty", "dwarf", "dynamic", "eager", "eagle", "early",
        "earth", "easily", "east", "easy", "echo", "ecology", "economy", "edge", "edit",
        "effort", "egg", "eight", "either", "elbow", "elder", "electric", "elegant", "element",
        "elevator", "elite", "else", "embark", "embody", "embrace", "emerge", "emotion", "employ",
        "empty", "enable", "enact", "end", "endless", "endorse", "enemy", "energy", "enforce",
        "engine", "enhance", "enjoy", "enlist", "enough", "enrich", "enroll", "ensure", "enter",
        "entry", "envelope", "episode", "equal", "equip", "era", "erase", "erode", "erosion",
        "erupt", "escape", "essay", "essence", "estate", "eternal", "ethics", "evidence", "evil",
        "evolve", "exact", "example", "excess", "exchange", "excite", "exclude", "excuse",
        "exercise", "exhaust", "exhibit", "exile", "exist", "exit", "exotic", "expand", "expect",
        "explain", "expose", "express", "extend", "extra", "eye", "eyebrow", "fabric", "face",
        "fade", "faint", "faith", "fall", "false", "fame", "family", "famous", "fan", "fancy",
        "farm", "fashion", "fat", "fatal", "father", "fatigue", "fault", "favorite", "feature",
        "federal", "fee", "feed", "feel", "female", "fence", "festival", "fetch", "fever", "few",
        "fiction", "field", "figure", "file", "film", "filter", "final", "find", "fine", "finger",
        "fire", "firm", "first", "fiscal", "fish", "fit", "fitness", "fix", "flag", "flame",
        "flat", "flavor", "flee", "flight", "flip", "float", "flock", "floor", "flower", "fluid",
        "fly", "foam", "focus", "fog", "foil", "fold", "follow", "food", "foot", "force",
        "forget", "fork", "fortune", "forum", "forward", "fossil", "foster", "found", "fox",
        "frame", "frequent", "fresh", "friend", "fringe", "frog", "front", "frost", "frown",
        "fruit", "fuel", "fun", "funny", "furnace", "fury", "future", "gadget", "gain", "galaxy",
        "game", "gap", "garage", "garbage", "garden", "garlic", "garment", "gas", "gasp", "gate",
        "gauge", "gaze", "general", "genius", "genre", "gentle", "genuine", "gesture", "ghost",
        "gift", "giggle", "ginger", "giraffe", "girl", "give", "glad", "glance", "glare", "glass",
        "glimpse", "globe", "gloom", "glory", "glove", "glow", "glue", "goat", "goddess", "gold",
        "goose", "gorilla", "gospel", "gossip", "govern", "gown", "grab", "grace", "grain",
        "grape", "grass", "gravity", "great", "green", "grid", "grief", "grit", "grocery",
        "grow", "grunt", "guard", "guess", "guide", "guilt", "guitar", "gun", "gym", "habit",
        "half", "hammer", "hamster", "hand", "happy", "harbor", "hard", "harsh", "harvest", "hat",
        "hawk", "hazard", "head", "health", "heart", "heavy", "hedgehog", "height", "hello",
        "help", "hen", "hero", "hidden", "high", "hill", "hint", "hip", "hire", "history",
        "hockey", "hold", "hole", "holiday", "hollow", "home", "honey", "hood", "hope", "horn",
        "horse", "hospital", "host", "hotel", "hour", "hover", "hub", "huge", "human", "humble",
        "hundred", "hungry", "hunt", "hurdle", "hurry", "hurt", "husband", "hybrid", "ice",
        "idea", "identify", "idle", "ignore", "ill", "illegal", "illness", "image", "imitate",
        "immune", "impact", "impose", "improve", "impulse", "inch", "include", "income",
        "index", "indicate", "indoor", "industry", "infant", "inflict", "inform", "inhale",
        "initial", "inject", "injury", "inmate", "inner", "innocent", "input", "inquiry",
        "insect", "inside", "inspire", "install", "intact", "interest", "into", "invest",
        "involve", "iron", "island", "isolate", "issue", "item", "ivory", "jacket", "jaguar",
        "jazz", "jealous", "jeans", "jelly", "jewel", "job", "join", "joke", "journey", "joy",
        "juice", "jump", "jungle", "junior", "junk", "just", "kangaroo", "keen", "keep",
        "key", "kick", "kid", "kidney", "kind", "kingdom", "kiss", "kit", "kitchen", "kite",
        "kiwi", "knee", "knife", "knock", "know", "lab", "label", "labor", "ladder", "lady",
        "lamp", "language", "laptop", "large", "later", "latin", "laugh", "laundry", "lava",
        "lawn", "lawsuit", "layer", "lazy", "leader", "leaf", "learn", "leave", "lecture", "left",
        "legal", "legend", "leisure", "lemon", "lend", "length", "lens", "leopard", "lesson",
        "level", "liar", "liberty", "library", "license", "life", "lift", "light", "like", "limb",
        "link", "lion", "liquid", "list", "little", "live", "lizard", "load", "loan", "lobster",
        "lock", "logic", "lonely", "long", "loop", "lottery", "loud", "lounge", "love", "loyal",
        "luggage", "lumber", "lunar", "lunch", "luxury", "lyrics", "machine", "mad", "magic",
        "maid", "mail", "main", "major", "make", "mammal", "man", "manage", "mandate", "mango",
        "manual", "maple", "marble", "march", "margin", "marine", "market", "marriage", "mask",
        "master", "match", "material", "math", "matrix", "matter", "maximum", "maze", "meadow",
        "measure", "meat", "mechanic", "medal", "media", "melody", "melt", "member", "memory",
        "menu", "mercy", "merge", "merit", "merry", "mesh", "message", "metal", "method",
        "midnight", "milk", "million", "mimic", "mind", "minimum", "minor", "minute", "miracle",
        "misery", "miss", "mistake", "mix", "mixed", "mixture", "mobile", "model", "modify",
        "moment", "monitor", "monkey", "monster", "month", "moon", "moral", "more", "morning",
        "mother", "motion", "motor", "mountain", "mouse", "move", "movie", "much", "muffin",
        "multiply", "muscle", "museum", "mushroom", "music", "must", "mutual", "myself",
        "myth", "naive", "name", "napkin", "narrow", "nasty", "nation", "nature", "near", "neck",
        "negative", "neglect", "neither", "nephew", "nerve", "nest", "net", "network", "neutral",
        "news", "next", "nice", "night", "noble", "noise", "nominee", "noodle", "normal", "north",
        "notable", "note", "nothing", "notice", "novel", "now", "nuclear", "number", "nurse",
        "oak", "obey", "object", "oblige", "obscure", "observe", "obtain", "obvious", "occur",
        "october", "odor", "off", "offer", "office", "often", "oil", "okay", "old", "olive",
        "omit", "once", "one", "onion", "online", "only", "open", "opera", "opinion", "oppose",
        "orange", "orbit", "orchard", "order", "ordinary", "organ", "orient", "original",
        "ostrich", "other", "outdoor", "outer", "output", "outside", "oval", "oven", "over",
        "owner", "oxygen", "oyster", "ozone", "pact", "paddle", "page", "pair", "palace", "palm",
        "panel", "panic", "panther", "paper", "parade", "parent", "park", "parrot", "party",
        "patch", "path", "patient", "patrol", "pattern", "pause", "pave", "payment", "peace",
        "pear", "peasant", "pelican", "pen", "penalty", "pencil", "people", "pepper", "perfect",
        "person", "pet", "phone", "photo", "phrase", "physical", "piano", "picnic", "picture",
        "pig", "pigeon", "pill", "pilot", "pink", "pioneer", "pipe", "pistol", "pitch", "pizza",
        "planet", "plastic", "plate", "play", "please", "pledge", "pluck", "plug", "plunge",
        "poet", "point", "polar", "pole", "police", "pond", "pony", "pool", "popular", "portion",
        "possible", "post", "potato", "pottery", "poverty", "powder", "power", "practice",
        "predict", "prefer", "prepare", "present", "pretty", "prevent", "price", "pride",
        "print", "priority", "prison", "private", "prize", "problem", "process", "produce",
        "program", "project", "promote", "proof", "property", "prosper", "protect", "proud",
        "public", "pudding", "pull", "pulp", "pulse", "pumpkin", "punch", "pupil", "puppy",
        "purity", "purpose", "purse", "push", "put", "puzzle", "pyramid", "quality", "quantum",
        "question", "quick", "quit", "quiz", "quote", "rabbit", "raccoon", "race", "rack",
        "radio", "rail", "rain", "raise", "rally", "ramp", "ranch", "random", "range", "rapid",
        "rate", "rather", "raven", "raw", "razor", "ready", "real", "reason", "rebel", "rebuild",
        "receive", "recipe", "record", "recycle", "reduce", "reflect", "reform", "refuse",
        "regret", "regular", "reject", "relax", "release", "relief", "rely", "remain", "remember",
        "remove", "render", "renew", "rent", "reopen", "repair", "repeat", "replace", "report",
        "rescue", "resemble", "resist", "resource", "response", "result", "retire", "retreat",
        "reunion", "reveal", "review", "reward", "rhythm", "rib", "ribbon", "rice", "rich",
        "ridge", "rifle", "right", "rigid", "ring", "riot", "ripple", "risk", "ritual", "rival",
        "road", "roast", "robot", "robust", "rocket", "romance", "roof", "rookie", "room", "rose",
        "rough", "round", "route", "royal", "rubber", "rude", "rug", "rule", "run", "runway",
        "sad", "saddle", "sadness", "safe", "sail", "salad", "salmon", "salon", "salt", "salute",
        "sample", "sand", "satisfy", "satoshi", "sauce", "sausage", "save", "say", "scale",
        "scare", "scatter", "scene", "scheme", "school", "science", "scissors", "scorpion",
        "scrap", "screen", "script", "scrub", "sea", "search", "season", "seat", "second",
        "section", "security", "seed", "seek", "segment", "select", "sell", "seminar", "senior",
        "sentence", "series", "service", "session", "settle", "setup", "seven", "shadow", "shaft",
        "share", "shed", "shell", "sheriff", "shield", "shift", "shine", "ship", "shiver",
        "shoe", "shoot", "shop", "short", "shoulder", "shove", "shrimp", "shrug", "shuffle",
        "sibling", "sick", "side", "siege", "sight", "sign", "silent", "silk", "silly", "silver",
        "simple", "since", "sing", "siren", "sister", "situate", "six", "size", "skate", "sketch",
        "skill", "skin", "skirt", "skull", "slab", "slam", "sleep", "slender", "slice", "slide",
        "slim", "slogan", "slot", "slow", "slush", "small", "smart", "smile", "smoke", "smooth",
        "snake", "snap", "sniff", "snow", "soap", "soccer", "social", "sock", "soda", "soft",
        "soldier", "solid", "solution", "solve", "someone", "song", "soon", "sorry", "sort",
        "sound", "soup", "source", "south", "space", "spare", "spatial", "spawn", "speak",
        "speed", "spell", "spend", "sphere", "spice", "spider", "spike", "spin", "spirit",
        "spoil", "sponsor", "spoon", "sport", "spot", "spray", "spread", "spring", "spy",
        "squeeze", "squirrel", "stable", "stadium", "staff", "stage", "stairs", "stamp", "stand",
        "state", "stay", "steak", "steel", "stem", "step", "stereo", "stick", "still", "sting",
        "stomach", "stone", "stool", "story", "stove", "strategy", "street", "strike", "strong",
        "student", "stuff", "stumble", "style", "subject", "submit", "subway", "success", "such",
        "suffer", "sugar", "suggest", "suit", "summer", "sun", "sunny", "sunset", "super",
        "supreme", "sure", "surface", "surge", "surprise", "surround", "survey", "suspect",
        "swallow", "swamp", "swap", "swarm", "swear", "sweet", "swift", "swim", "swing", "switch",
        "symbol", "symptom", "syrup", "system", "table", "tackle", "tag", "tail", "talent",
        "tank", "tape", "target", "task", "taste", "tattoo", "taxi", "teach", "team", "tell",
        "tenant", "tennis", "tent", "term", "test", "text", "thank", "that", "theme", "then",
        "there", "they", "thing", "this", "thought", "three", "thrive", "throw", "thumb",
        "ticket", "tide", "tiger", "tilt", "timber", "time", "tiny", "tip", "tired", "tissue",
        "toast", "tobacco", "today", "toddler", "toe", "together", "toilet", "token", "tomato",
        "tone", "tongue", "tonight", "tool", "tooth", "top", "topic", "topple", "torch",
        "tortoise", "toss", "total", "tourist", "toward", "tower", "town", "toy", "track",
        "traffic", "tragic", "train", "transfer", "trap", "trash", "travel", "tray", "treat",
        "trend", "trial", "tribe", "trick", "trigger", "trim", "trip", "trophy", "trouble",
        "true", "truly", "trumpet", "trust", "truth", "try", "tube", "tuition", "tumble", "tuna",
        "turkey", "turn", "turtle", "twelve", "twenty", "twice", "twin", "twist", "two", "type",
        "ugly", "umbrella", "unable", "unaware", "uncle", "uncover", "under", "undo", "unfair",
        "unhappy", "uniform", "unique", "unit", "universe", "unknown", "unlock", "until",
        "unveil", "update", "upgrade", "uphold", "upon", "upper", "upset", "urban", "urge",
        "use", "used", "useful", "useless", "usual", "utility", "vacant", "vacuum", "vague",
        "valley", "valve", "van", "vanish", "vapor", "various", "vast", "vault", "vehicle",
        "vendor", "venture", "venue", "verb", "verify", "version", "very", "vessel", "veteran",
        "vibrant", "vicious", "victory", "video", "view", "village", "vintage", "violin",
        "virus", "visa", "visit", "visual", "vital", "vivid", "vocal", "voice", "void", "volcano",
        "vote", "voyage", "wage", "wagon", "wait", "walk", "wall", "walnut", "want", "warfare",
        "warrior", "wash", "wasp", "waste", "water", "wave", "way", "wealth", "weapon", "wear",
        "weather", "web", "wedding", "weekend", "weird", "welcome", "west", "wet", "whale",
        "wheat", "wheel", "when", "where", "whip", "whisper", "wide", "width", "wife", "wild",
        "win", "window", "wine", "wing", "wink", "winner", "winter", "wire", "wisdom", "wise",
        "witness", "wolf", "woman", "wonder", "wood", "wool", "word", "work", "world", "worry",
        "wrap", "wreck", "wrestle", "wrist", "write", "wrong", "yard", "year", "yellow", "you",
        "youth", "zebra", "zero", "zone", "zoo"
    ]
}
